"""updated client testimonial

Revision ID: 35c50e115b0c
Revises: 9da377c87cae
Create Date: 2025-05-07 14:10:14.553435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35c50e115b0c'
down_revision = '9da377c87cae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_testimonial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_client_testimonial_user_id_user'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_testimonial', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_client_testimonial_user_id_user'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
