"""removed client table

Revision ID: 4b7c0d1e4dc3
Revises: 35c50e115b0c
Create Date: 2025-05-08 22:02:08.013808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b7c0d1e4dc3'
down_revision = '35c50e115b0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('image', sa.VARCHAR(length=10000), nullable=True),
    sa.Column('name', sa.VARCHAR(length=150), nullable=True),
    sa.Column('organization', sa.VARCHAR(length=10000), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_client_user_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_client')
    )
    # ### end Alembic commands ###
