"""updated contact section table

Revision ID: 593adfacf757
Revises: 4b7c0d1e4dc3
Create Date: 2025-05-08 23:17:24.251242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '593adfacf757'
down_revision = '4b7c0d1e4dc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_section', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_section', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
