"""Initial migration

Revision ID: 686cf3e00a1e
Revises: 
Create Date: 2025-05-04 10:40:41.392873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686cf3e00a1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_location'))
    )
    op.create_table('tool',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool')),
    sa.UniqueConstraint('name', name=op.f('uq_tool_name'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('public_id', name=op.f('uq_user_public_id')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'))
    )
    op.create_table('about_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paragraph1', sa.String(length=300), nullable=True),
    sa.Column('skills_intro', sa.String(length=100), nullable=True),
    sa.Column('paragraph2', sa.String(length=300), nullable=True),
    sa.Column('picture', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_about_section_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_about_section')),
    sa.UniqueConstraint('user_id', name=op.f('uq_about_section_user_id'))
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=10000), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('organization', sa.String(length=10000), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_client_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client'))
    )
    op.create_table('contact_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intro_text', sa.String(length=10000), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('contact_email', sa.String(length=150), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_contact_section_location_id_location')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_contact_section_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_section')),
    sa.UniqueConstraint('contact_email', name=op.f('uq_contact_section_contact_email'))
    )
    op.create_table('experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=150), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_experience_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experience'))
    )
    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('resume', sa.String(length=150), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_pic', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_portfolio_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio')),
    sa.UniqueConstraint('user_id', name=op.f('uq_portfolio_user_id'))
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('highlight', sa.Boolean(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_project_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project'))
    )
    op.create_table('services_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intro_text', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_services_section_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services_section')),
    sa.UniqueConstraint('user_id', name=op.f('uq_services_section_user_id'))
    )
    op.create_table('about_tools',
    sa.Column('about_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['about_id'], ['about_section.id'], name=op.f('fk_about_tools_about_id_about_section')),
    sa.ForeignKeyConstraint(['tool_id'], ['tool.id'], name=op.f('fk_about_tools_tool_id_tool')),
    sa.PrimaryKeyConstraint('about_id', 'tool_id', name=op.f('pk_about_tools'))
    )
    op.create_table('experience_bullet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bullet_point', sa.String(length=500), nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experience.id'], name=op.f('fk_experience_bullet_experience_id_experience')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experience_bullet'))
    )
    op.create_table('project_tools',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_project_tools_project_id_project')),
    sa.ForeignKeyConstraint(['tool_id'], ['tool.id'], name=op.f('fk_project_tools_tool_id_tool')),
    sa.PrimaryKeyConstraint('project_id', 'tool_id', name=op.f('pk_project_tools'))
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.Column('services_section_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['services_section_id'], ['services_section.id'], name=op.f('fk_service_services_section_id_services_section')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service'))
    )
    op.create_table('social_link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_type', sa.String(length=150), nullable=False),
    sa.Column('link_value', sa.String(length=2000), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], name=op.f('fk_social_link_portfolio_id_portfolio')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_link'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('social_link')
    op.drop_table('service')
    op.drop_table('project_tools')
    op.drop_table('experience_bullet')
    op.drop_table('about_tools')
    op.drop_table('services_section')
    op.drop_table('project')
    op.drop_table('portfolio')
    op.drop_table('experience')
    op.drop_table('contact_section')
    op.drop_table('client')
    op.drop_table('about_section')
    op.drop_table('user')
    op.drop_table('tool')
    op.drop_table('location')
    # ### end Alembic commands ###
