"""client testimonial

Revision ID: 9da377c87cae
Revises: 686cf3e00a1e
Create Date: 2025-05-07 13:57:07.472344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da377c87cae'
down_revision = '686cf3e00a1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_testimonial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=10000), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('testimonial', sa.String(length=150), nullable=False),
    sa.Column('organization', sa.String(length=10000), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_testimonial'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_testimonial')
    # ### end Alembic commands ###
