"""updated contact section

Revision ID: f6e03f878110
Revises: d230be0b5465
Create Date: 2025-05-09 11:08:56.887302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6e03f878110'
down_revision = 'd230be0b5465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_section', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_contact_section_user_id'), ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_section', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_contact_section_user_id'), type_='unique')

    # ### end Alembic commands ###
